.Dd $Mdocdate: August 23 2015 $
.Dt 9PFS 1
.Os
.Sh NAME
.Nm 9pfs
.Nd mount 9P service via FUSE
.Sh SYNOPSIS
.Nm grep
.Bk -words
.Op Fl adnu
.Op Fl p Ar port
.Op Ar host
.Op Ar mtpt
.Ek
.Sh DESCRIPTION
.Nm 9pfs
mounts the 9P service running at
.Ar host
onto
.Ar mtpt
using the FUSE user-level file system driver.
.Pp
More stuff.
.Sh EXAMPLES
Foo bar.